#ifndef COUNTRY_RELOCATION_RANKING_SYSTEM_INCLUDE_COUNTRY_H_
#define COUNTRY_RELOCATION_RANKING_SYSTEM_INCLUDE_COUNTRY_H_

class Country {

};

#endif //COUNTRY_RELOCATION_RANKING_SYSTEM_INCLUDE_COUNTRY_H_
