#ifndef COUNTRY_RELOCATION_RANKING_SYSTEM__I_DB_MANAGER_H_
#define COUNTRY_RELOCATION_RANKING_SYSTEM__I_DB_MANAGER_H_

class IDBManager {

};

#endif //COUNTRY_RELOCATION_RANKING_SYSTEM__I_DB_MANAGER_H_
